#!/usr/bin/env ruby
require 'serialport'

system("stty raw -echo") #=> Raw mode, no echo
puts 'Opening serial port...'
sp = SerialPort.open "/dev/tty.HC-06-DevB", 9600

puts "Port opened."

loop do
  char = STDIN.getc
  break if char == "q"
  sp.write char 
end

sp.close
puts "Port closed."
system("stty -raw echo") #=> Reset terminal mode 
